### ISSUE TITLE
Practica de conexión 

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-confident-students#1]
[PRACTICA DE CONEXIÓN.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-confident-students/files/15458512/PRACTICA.DE.CONEXION.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..

**Comment by josealfredo79** [comment]
Bien hecho y revisado..Calificacion 20
